name: presentation
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  application: any
  foundation: any
  infrastructure: any
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  go_router: ^16.2.5
  google_fonts: ^6.3.2
  url_launcher: ^6.3.2
  url_launcher_web: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: any
  go_router_builder: 4.1.0
  build_verify: any
  custom_lint: any
  json_serializable: ^6.11.1
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/google_fonts/
