[workspace]
resolver = "3"

members = [
    "crates/application",
    "crates/domain",
    "crates/infrastructure",
    "crates/shared",
    "servers/api",
    "servers/batch",
    "servers/internal_api",
    "servers/projector",
]
